### ISSUE TITLE
how to ignore fonts ?

### ISSUE THREAD

**Issue by stephanedemotte** [sairion/svg-inline-loader#20]
Hi !

I have some svg to inline but, i load fonts too..

with this test  
```
    {
        test: /\.svg$/,
        loader: 'svg-inline'
    }
```

How can i ignore fonts ?

thanks !

**Comment by sairion** [comment]
Hi! You need to set 'include' or 'exclude' option to selectively use loader. Usually Webpack loaders don't choose which file to load and it is totally up to configuration. Mine is same as most of loaders do :).

See https://webpack.github.io/docs/configuration.html#module-loaders for more information. I'm closing, since it's more like general Webpack question.

**Comment by OrganicPanda** [comment]
@stephanedemotte I found the solution was a bit more complicated because you don't want your fonts inline and you don't want your inline SVGs to go through the same loader as your fonts (probably). This config is working for me:

```js 
{
  test: /font.*\.(ttf|eot|svg|woff(2)?)(\?[a-z0-9-]+)?$/,
  loader: 'file-loader'
},
{
  test: /\.svg$/,
  loader: 'svg-inline'
}
```

So if the path contains `font` I use `file-loader` otherwise `svg-inline`. I'm new to Webpack though so this might be dumb!

**Comment by stephanedemotte** [comment]
You rock ! Thanks !

**Comment by natemate90** [comment]
Thanks! I got the fonts working by adding this: 
`    config.module.rules.push({
        test: /fonts.*\.svg$/,
        loader: 'url-loader'
      },
      {
        test: /\.svg$/,
        loader: 'svg-inline-loader'
      })
`
